### ISSUE TITLE
What will we use to establish and administer the project plan?

### ISSUE THREAD

**Issue by sergeantbacon** [BayoAdejare/Leverage#2]
We need to maintain a basic project plan. What technology/platform should we use for this?

**Comment by BayoAdejare** [comment]
Trello?

**Comment by sergeantbacon** [comment]
We're going to use waffle.io for visualizing the workflow, but we need to host a project plan somewhere. I'll look into it but would love it if anyone had recommendations.

**Comment by caseyvaughan** [comment]
Any recommendations?

**Comment by jaccat** [comment]
I think some sort of gantt chart plugin would work well for a big picture project plan. I have been looking to see if there is something that works with GitHub (and that is also free:)!) but I haven't really found anything yet. We could always just create something simple in google docs excel. 

I did find a mind mapping tool that we might be able to use (https://sketchboard.io/), if not for the project plan itself then for brainstorming, strategy, roadmaps and general idea organizing. While Sketchboard is free there is a limit to how many people on the team may use it, which may or may not be a problem depending on how we use it. Also it integrates into GitHub.

I'll keep looking!

**Comment by sergeantbacon** [comment]
Been doing more research and I can't seem to find anything that does project plans that live in the interwebs without having to pay a monthly fee.

I think I'll just throw something together in Google Sheets. Stay tuned.

**Comment by Kistine** [comment]
Not sure if this would fit your goals, but Elegantt integrates with Trello: https://elegantt.com/

**Comment by jaccat** [comment]
Elegantt looks really great and I love the name:). They unfortunately don't integrate into GitHub yet:(

**Comment by sergeantbacon** [comment]
Jacqui whipped up a nice Gantt chart in Google Sheets. Strategy team will add a copy of the chart to the repo if/when it's needed.
