### ISSUE TITLE
DB password is in code

### ISSUE THREAD

**Issue by eamoncaddigan** [BayoAdejare/Leverage#3]
We need to change the password of the demhack2016 user and not store it in code all over the repo.

**Comment by BayoAdejare** [comment]
This is actually a big security issue I intentionally left. To speed development I left the settings.py file in the repo this includes the db password (and the secret key). After removal of the settings file including those in previous versions, we'll need to change the secret key and db password.

**Comment by BayoAdejare** [comment]
I added settings.py to.gitignore so the settings file is removed from the current version and is no longer tracked. It is still in previous versions but that does not matter as we're going to create new secret key and db password.

**Comment by eamoncaddigan** [comment]
Yeah, it's a problem in my code too--I definitely didn't want to single anybody out. 

I've changed the password of the demhack2016 account in the DB. Anybody who has shell access to our server can get the new one in the file ~eamon/DBLOGIN.txt. I just confirmed that everything still works okay with the new password.

**Comment by BayoAdejare** [comment]
Thanks Eamon

**Comment by eamoncaddigan** [comment]
I don't want to forget to make changes in the analysis stuff.

**Comment by eamoncaddigan** [comment]
Fixed all of the R scripts outside the preprocessing stuff, as these are meant to be run once.
